export type ToolKey = "gmail" | "drive" | "docs" | "sheets" | "calendar";

export type SeedEntity = {
  id: string;
  kind: string;
  label: string;
  meta?: string;
};

// Stagnant (hard-coded) entity graph for Pleasure Pizza — a local pizza
// shop right next to campus. Every entry here is what the brain treats
// as "pulled from this account." Nothing is fetched from Composio at
// runtime — the brain auto-populates from this file after the agent
// learns which services the user mentioned.

export const seedData: Record<ToolKey, SeedEntity[]> = {
  gmail: [
    { id: "theta-chi-catering", kind: "Email", label: "Theta Chi — Friday catering", meta: "Unread · 2h ago" },
    { id: "marco-cheese", kind: "Email", label: "Marco's Cheese — weekly invoice", meta: "Auto-sent Mon" },
    { id: "mom-feedback", kind: "Email", label: "Mom — feedback on new menu item", meta: "3d ago" },
    { id: "delivery-roster", kind: "Email", label: "Delivery driver roster", meta: "From Aisha" },
    { id: "health-inspector", kind: "Email", label: "Health inspector follow-up", meta: "Awaiting reply" },
    { id: "kappa-alpha-pizza-night", kind: "Email", label: "Kappa Alpha — pizza night RSVP", meta: "42 confirmed" },
    { id: "delta-gamma-brunch", kind: "Email", label: "Delta Gamma — Sunday brunch order", meta: "Replied" },
    { id: "supplier-flour", kind: "Email", label: "Caputo Flour — backorder notice", meta: "Resolved" },
    { id: "supplier-tomatoes", kind: "Email", label: "San Marzano tomatoes — quote", meta: "Awaiting" },
    { id: "instagram-dm", kind: "Email", label: "Instagram — collab request", meta: "@foodieanna" },
    { id: "yelp-review", kind: "Email", label: "Yelp — 5-star review notification", meta: "Auto" },
    { id: "yelp-complaint", kind: "Email", label: "Yelp — 2-star review reply needed", meta: "From: J. Tan" },
    { id: "leasing-renewal", kind: "Email", label: "Landlord — lease renewal", meta: "Due Nov" },
    { id: "pos-vendor", kind: "Email", label: "Toast POS — monthly statement", meta: "Auto" },
    { id: "payroll-stubs", kind: "Email", label: "Gusto — payroll stubs", meta: "Weekly" },
    { id: "fire-inspection", kind: "Email", label: "Fire dept — annual inspection", meta: "Nov 14" },
    { id: "loud-music", kind: "Email", label: "City council — noise complaint", meta: "Replied" },
    { id: "lost-and-found", kind: "Email", label: "Lost & found — AirPods query", meta: "Awaiting" },
    { id: "courier-glitches", kind: "Email", label: "DoorDash — courier delay report", meta: "3 incidents" },
    { id: "student-discount", kind: "Email", label: "Student Affairs — discount program", meta: "Confirmed" },
    { id: "charity-event", kind: "Email", label: "Local Food Bank — donation ask", meta: "Replied" },
    { id: "catering-template", kind: "Email", label: "Catering template reply", meta: "Drafted" },
    { id: "instagram-feature", kind: "Email", label: "Campus Mag — feature request", meta: "Yes" },
    { id: "staff-complaint", kind: "Email", label: "Anonymous staff feedback", meta: "Replied" },
    { id: "flyer-approval", kind: "Email", label: "Marketing — finals week flyer", meta: "Approved" },
    { id: "oven-broken", kind: "Email", label: "Marco — oven #2 broken", meta: "URGENT" },
    { id: "late-shipment", kind: "Email", label: "Sysco — late pepperoni shipment", meta: "Awaiting" },
    { id: "loved-by-fan", kind: "Email", label: "Regular customer — thank you", meta: "1mo ago" },
  ],
  drive: [
    { id: "menu-v7", kind: "PDF", label: "Pleasure Pizza Menu v7.pdf", meta: "Updated yesterday" },
    { id: "supplier-list", kind: "Document", label: "Supplier list — Q4", meta: "Owned by Aisha" },
    { id: "marketing-flyer", kind: "PDF", label: "Finals week flyer", meta: "Shared with team" },
    { id: "dough-recipe", kind: "PDF", label: "Pizza dough recipe (master)", meta: "Last edited Sep" },
    { id: "allergen-sheet", kind: "Document", label: "Allergen info sheet", meta: "Posted on counter" },
    { id: "menu-v6-archive", kind: "PDF", label: "Menu v6 (archived)", meta: "Aug 2026" },
    { id: "menu-game-day", kind: "PDF", label: "Game Day special menu", meta: "Football only" },
    { id: "menu-finals-week", kind: "PDF", label: "Finals week late-night menu", meta: "10pm-2am" },
    { id: "menu-graduation", kind: "PDF", label: "Graduation weekend catering", meta: "May 2026" },
    { id: "supplier-caputo-contract", kind: "PDF", label: "Caputo contract 2026", meta: "Signed Jan" },
    { id: "supplier-sysco-contract", kind: "PDF", label: "Sysco master agreement", meta: "Auto-renew" },
    { id: "supplier-cheese-pricing", kind: "Spreadsheet", label: "Cheese vendor pricing", meta: "Q4 update" },
    { id: "training-new-hire-deck", kind: "Presentation", label: "New hire training deck", meta: "24 slides" },
    { id: "training-food-safety", kind: "Document", label: "ServSafe food safety", meta: "2026 ed." },
    { id: "training-allergen", kind: "Document", label: "Allergen training", meta: "Video + quiz" },
    { id: "photo-pizza-1", kind: "Image", label: "Hero shot — Margherita", meta: "Web hero" },
    { id: "photo-pizza-2", kind: "Image", label: "Hero shot — Pepperoni", meta: "Web hero" },
    { id: "photo-storefront", kind: "Image", label: "Storefront — sunset", meta: "Instagram" },
    { id: "photo-pizza-line", kind: "Image", label: "Pizza line rush", meta: "Story" },
    { id: "logo-master", kind: "Image", label: "Pleasure Pizza logo (master)", meta: "SVG + PNG" },
    { id: "logo-mono", kind: "Image", label: "Logo — monochrome", meta: "For print" },
    { id: "permit-food-service", kind: "PDF", label: "Food service permit", meta: "Expires Mar 2027" },
    { id: "permit-business", kind: "PDF", label: "Business license", meta: "Annual" },
    { id: "permit-signage", kind: "PDF", label: "Signage permit", meta: "City" },
    { id: "insurance-gl", kind: "PDF", label: "General liability insurance", meta: "Annual" },
    { id: "insurance-workers-comp", kind: "PDF", label: "Workers comp insurance", meta: "Annual" },
    { id: "handbook", kind: "Document", label: "Employee handbook v4", meta: "Updated Aug" },
    { id: "manuals-toast", kind: "PDF", label: "Toast POS manual", meta: "For staff" },
    { id: "manuals-oven", kind: "PDF", label: "Blodgett oven manual", meta: "For repairs" },
    { id: "recipe-marinara", kind: "Document", label: "Marinara recipe (master)", meta: "Last edited Jul" },
    { id: "recipe-pesto", kind: "Document", label: "Pesto recipe", meta: "House" },
    { id: "recipe-ranch", kind: "Document", label: "House ranch", meta: "Walk-in only" },
  ],
  docs: [
    { id: "new-hire-training", kind: "Doc", label: "New hire training", meta: "12 sections" },
    { id: "opening-checklist", kind: "Doc", label: "Opening checklist", meta: "Used daily" },
    { id: "closing-checklist", kind: "Doc", label: "Closing checklist", meta: "Used daily" },
    { id: "pizza-station-sop", kind: "Doc", label: "Pizza station SOP", meta: "v3.2" },
    { id: "cash-handling", kind: "Doc", label: "Cash handling guide", meta: "Reviewed Sep" },
    { id: "delivery-procedure", kind: "Doc", label: "Delivery procedure", meta: "DoorDash + in-house" },
    { id: "phone-etiquette", kind: "Doc", label: "Phone etiquette guide", meta: "v2.0" },
    { id: "complaint-handling", kind: "Doc", label: "Customer complaint handling", meta: "Last edited Aug" },
    { id: "allergy-protocol", kind: "Doc", label: "Allergy incident protocol", meta: "CRITICAL" },
    { id: "fire-evacuation", kind: "Doc", label: "Fire evacuation plan", meta: "Reviewed Apr" },
    { id: "emergency-contacts", kind: "Doc", label: "Emergency contacts", meta: "Posted by phone" },
    { id: "food-allergen-chart", kind: "Doc", label: "Food allergen chart", meta: "Updated Aug" },
    { id: "temperature-log", kind: "Doc", label: "Walk-in temperature log", meta: "Daily 2x" },
    { id: "shift-swap", kind: "Doc", label: "Shift swap policy", meta: "v1.5" },
    { id: "tip-distribution", kind: "Doc", label: "Tip distribution formula", meta: "Hours + role" },
    { id: "dress-code", kind: "Doc", label: "Dress code", meta: "Updated Jun" },
    { id: "social-media-policy", kind: "Doc", label: "Social media policy", meta: "v1.0" },
    { id: "catering-onboarding", kind: "Doc", label: "Catering onboarding", meta: "For new customers" },
    { id: "catering-pricing", kind: "Doc", label: "Catering pricing tiers", meta: "2026" },
    { id: "menu-development", kind: "Doc", label: "Menu development playbook", meta: "Quarterly" },
    { id: "inventory-count", kind: "Doc", label: "Inventory count procedure", meta: "Weekly" },
    { id: "equipment-cleaning", kind: "Doc", label: "Equipment cleaning schedule", meta: "Mon/Wed/Fri" },
    { id: "pest-control", kind: "Doc", label: "Pest control log", meta: "Monthly" },
    { id: "trash-recycling", kind: "Doc", label: "Trash + recycling SOP", meta: "Updated May" },
    { id: "customer-loyalty", kind: "Doc", label: "Customer loyalty program design", meta: "Draft" },
    { id: "vendor-onboarding", kind: "Doc", label: "New vendor onboarding", meta: "For Aisha" },
    { id: "staff-onboarding", kind: "Doc", label: "Staff onboarding week plan", meta: "5-day" },
    { id: "incident-report", kind: "Doc", label: "Incident report template", meta: "Form" },
    { id: "marketing-calendar", kind: "Doc", label: "Marketing calendar template", meta: "Q4" },
  ],
  sheets: [
    { id: "inventory-oct", kind: "Sheet", label: "Inventory tracker — Oct", meta: "Auto-updating" },
    { id: "weekly-sales", kind: "Sheet", label: "Weekly sales", meta: "52 weeks" },
    { id: "staff-schedule", kind: "Sheet", label: "Staff schedule — Oct", meta: "Owned by Marco" },
    { id: "top-sellers", kind: "Sheet", label: "Top sellers by week", meta: "Live" },
    { id: "catering-orders", kind: "Sheet", label: "Catering orders", meta: "Q4" },
    { id: "supplier-pricing", kind: "Sheet", label: "Supplier price comparison", meta: "Monthly" },
    { id: "food-cost", kind: "Sheet", label: "Food cost % by item", meta: "Auto" },
    { id: "labor-cost", kind: "Sheet", label: "Labor cost % by week", meta: "Auto" },
    { id: "tips-tracking", kind: "Sheet", label: "Tips by shift", meta: "Weekly" },
    { id: "delivery-metrics", kind: "Sheet", label: "Delivery time metrics", meta: "DoorDash" },
    { id: "waste-log", kind: "Sheet", label: "Waste log", meta: "Daily" },
    { id: "customer-count", kind: "Sheet", label: "Customer count by hour", meta: "POS" },
    { id: "top-customers", kind: "Sheet", label: "Top 100 customers", meta: "By spend" },
    { id: "email-subscriber-list", kind: "Sheet", label: "Email subscriber list", meta: "1,247" },
    { id: "social-followers", kind: "Sheet", label: "Social follower counts", meta: "Weekly" },
    { id: "review-tracker", kind: "Sheet", label: "Review tracker", meta: "Yelp+Google" },
    { id: "competitor-pricing", kind: "Sheet", label: "Competitor pricing", meta: "Q3" },
    { id: "expenses-monthly", kind: "Sheet", label: "Monthly expenses", meta: "Auto-import" },
    { id: "p-and-l", kind: "Sheet", label: "P&L summary", meta: "Monthly" },
    { id: "tax-deductions", kind: "Sheet", label: "Tax deduction log", meta: "For accountant" },
    { id: "equipment-maintenance", kind: "Sheet", label: "Equipment maintenance log", meta: "Active" },
    { id: "staff-hours", kind: "Sheet", label: "Staff hours by week", meta: "Payroll" },
    { id: "menu-matrix", kind: "Sheet", label: "Menu engineering matrix", meta: "Stars/Plowhorses" },
    { id: "catering-pipeline", kind: "Sheet", label: "Catering pipeline", meta: "Q4 forecast" },
    { id: "loyalty-redemptions", kind: "Sheet", label: "Loyalty redemptions", meta: "Draft" },
    { id: "supplier-deliveries", kind: "Sheet", label: "Supplier delivery schedule", meta: "Mon/Wed/Fri" },
    { id: "student-org-discounts", kind: "Sheet", label: "Student org discount usage", meta: "By org" },
    { id: "weather-impact", kind: "Sheet", label: "Weather → sales correlation", meta: "Auto" },
  ],
  calendar: [
    { id: "shift-marco", kind: "Event", label: "Marco — opening shift", meta: "Mon · 10:00" },
    { id: "dough-delivery", kind: "Event", label: "Dough delivery", meta: "Wed · 06:00" },
    { id: "theta-chi-pickup", kind: "Event", label: "Theta Chi — pickup", meta: "Fri · 19:30" },
    { id: "health-inspection", kind: "Event", label: "Health inspection", meta: "Oct 22 · 11:00" },
    { id: "staff-meeting", kind: "Event", label: "Weekly staff meeting", meta: "Sun · 17:00" },
    { id: "shift-aisha", kind: "Event", label: "Aisha — opening shift", meta: "Tue · 10:00" },
    { id: "shift-jordan", kind: "Event", label: "Jordan — closing shift", meta: "Tue · 16:00" },
    { id: "shift-priya", kind: "Event", label: "Priya — mid shift", meta: "Wed · 12:00" },
    { id: "shift-devon", kind: "Event", label: "Devon — closing shift", meta: "Wed · 16:00" },
    { id: "shift-leo", kind: "Event", label: "Leo — opening shift", meta: "Thu · 10:00" },
    { id: "shift-sam", kind: "Event", label: "Sam — closing shift", meta: "Thu · 16:00" },
    { id: "shift-marco-fri", kind: "Event", label: "Marco — Friday rush", meta: "Fri · 14:00" },
    { id: "shift-aisha-fri", kind: "Event", label: "Aisha — Friday closing", meta: "Fri · 18:00" },
    { id: "sysco-delivery", kind: "Event", label: "Sysco delivery", meta: "Mon · 07:00" },
    { id: "caputo-delivery", kind: "Event", label: "Caputo flour delivery", meta: "Wed · 06:00" },
    { id: "cheese-delivery", kind: "Event", label: "Marco's Cheese delivery", meta: "Thu · 09:00" },
    { id: "produce-delivery", kind: "Event", label: "Local produce delivery", meta: "Tue · 08:00" },
    { id: "kappa-alpha-pickup", kind: "Event", label: "Kappa Alpha — pizza night pickup", meta: "Sat · 19:00" },
    { id: "delta-gamma-brunch", kind: "Event", label: "Delta Gamma — Sunday brunch", meta: "Sun · 10:30" },
    { id: "study-group-catering", kind: "Event", label: "Bio 101 study group", meta: "Tue · 21:00" },
    { id: "study-group-2", kind: "Event", label: "CS 231 study group", meta: "Wed · 22:00" },
    { id: "study-group-3", kind: "Event", label: "Econ 201 study group", meta: "Thu · 20:00" },
    { id: "trash-pickup", kind: "Event", label: "Trash + recycling pickup", meta: "Tue/Fri · 06:00" },
    { id: "pest-control-visit", kind: "Event", label: "Pest control visit", meta: "1st Mon · 10:00" },
    { id: "fire-inspection-2", kind: "Event", label: "Fire dept inspection", meta: "Nov 14 · 14:00" },
    { id: "game-day-rush", kind: "Event", label: "Game Day rush", meta: "Sat · 11:00" },
    { id: "finals-week-rush", kind: "Event", label: "Finals week late-night rush", meta: "Dec 9-13 · 22:00" },
    { id: "holiday-closed", kind: "Event", label: "Thanksgiving — closed", meta: "Nov 28" },
    { id: "owner-meeting", kind: "Event", label: "Owner 1:1 — Marco", meta: "Mon · 09:00" },
  ],
};
