const DEFAULT_ORIGIN = 'https://mcp-production-110f.up.railway.app';

function escapeHtml(value) {
  return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
}

export function renderCrmPage(origin = DEFAULT_ORIGIN) {
  const safeOrigin = escapeHtml(origin.replace(/\/$/, ''));
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#eeecf8">
  <meta name="description" content="Pleasure Pizza customer operations.">
  <meta name="application-name" content="Pleasure CRM">
  <title>Pleasure Pizza CRM</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root{--ink:#181722;--muted:#777482;--canvas:#eceaf6;--surface:#fff;--surface-soft:#faf9fc;--line:#ebe9f0;--line-strong:#d9d5e3;--violet:#7467d8;--violet-soft:#f0eefc;--mint:#23b99b;--mint-soft:#e8fbf5;--red:#c75b6d;--red-soft:#fff0f3;--amber:#aa791c;--amber-soft:#fff8e6;--shadow:0 24px 70px rgba(53,45,91,.12)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;background:var(--canvas);color:var(--ink);font:15px/1.45 "DM Sans",sans-serif;-webkit-font-smoothing:antialiased}button,input,select,textarea{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(116,103,216,.22);outline-offset:2px}
    .page{min-height:100vh;padding:28px}.shell{max-width:1500px;min-height:calc(100vh - 56px);margin:0 auto;border:1px solid rgba(255,255,255,.8);border-radius:24px;background:var(--surface);box-shadow:var(--shadow);overflow:hidden}.topbar{height:78px;padding:0 28px;display:grid;grid-template-columns:230px minmax(0,1fr) 230px;align-items:center;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:10px;font-weight:700}.brandmark{width:34px;height:34px;display:grid;place-items:center;border-radius:50%;background:var(--violet);color:#fff;font-size:11px}.topnav{display:flex;align-items:center;justify-content:center;gap:4px}.topnav button{min-height:40px;padding:8px 20px;border:1px solid transparent;border-radius:22px;background:transparent;color:var(--muted);font-size:14px}.topnav button:hover{background:var(--surface-soft);color:var(--ink)}.topnav .active{border-color:var(--violet);background:#fff;color:var(--ink);font-weight:600}.top-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px}.sync{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:12px}.sync-dot{width:8px;height:8px;border-radius:50%;background:var(--mint);box-shadow:0 0 0 4px var(--mint-soft)}.sync-dot.waiting{background:#e0ae4a;box-shadow:0 0 0 4px var(--amber-soft)}.sync-dot.offline{background:var(--red);box-shadow:0 0 0 4px var(--red-soft)}.icon-btn{width:40px;height:40px;border:1px solid var(--line);border-radius:50%;background:#fff;color:var(--muted)}.logout{padding:8px 12px;border:0;background:transparent;color:var(--muted);font-size:13px}
    .body{padding:0 24px 28px}.heading{height:76px;display:flex;align-items:center;justify-content:space-between;gap:16px}.heading h1{margin:0;font-size:22px;letter-spacing:-.03em}.heading p{margin:3px 0 0;color:var(--muted);font-size:13px}.btn{min-height:40px;padding:8px 14px;border:1px solid var(--line-strong);border-radius:9px;background:#fff;color:var(--ink);font-size:13px;font-weight:600}.btn:hover{border-color:#bbb5cc;background:var(--surface-soft)}.btn-primary{border-color:var(--violet);background:var(--violet);color:#fff}.btn-primary:hover{background:#6254ca;color:#fff}.btn-danger{color:var(--red)}.btn-small{min-height:34px;padding:6px 10px}.dashboard{display:grid;grid-template-columns:minmax(0,1.7fr) 370px;gap:16px}.maincol,.sidecol{min-width:0;display:grid;align-content:start;gap:16px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line);border-radius:13px;overflow:hidden}.metric{min-height:108px;padding:18px;border-right:1px solid var(--line);background:#fff}.metric:last-child{border-right:0}.metric-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.metric-label{font-size:14px;font-weight:600}.delta{padding:3px 8px;border-radius:999px;background:var(--mint-soft);color:#158369;font-size:11px}.delta.attention{background:var(--red-soft);color:var(--red)}.metric-value{margin-top:19px;font-size:25px;font-weight:700;letter-spacing:-.04em;font-variant-numeric:tabular-nums}.metric-note{margin-left:8px;color:var(--muted);font-size:11px;font-weight:400;letter-spacing:0}
    .panel{border:1px solid var(--line);border-radius:13px;background:#fff;overflow:hidden}.panel-head{min-height:58px;padding:13px 17px;display:flex;align-items:center;justify-content:space-between;gap:14px;border-bottom:1px solid var(--line)}.panel-head h2{margin:0;font-size:15px}.panel-head p{margin:2px 0 0;color:var(--muted);font-size:12px}.search{position:relative}.search input{width:220px;height:36px;padding:0 12px 0 34px;border:1px solid var(--line-strong);border-radius:18px;background:#fff;color:var(--ink);font-size:13px}.search:before{content:"";position:absolute;left:13px;top:11px;width:9px;height:9px;border:1.5px solid var(--muted);border-radius:50%}.search:after{content:"";position:absolute;left:21px;top:21px;width:5px;height:1.5px;background:var(--muted);transform:rotate(45deg)}
    .table-wrap{overflow:auto}.table{width:100%;min-width:720px;border-collapse:collapse}.table th{padding:10px 14px;color:var(--muted);font-size:11px;font-weight:500;text-align:left}.table td{padding:11px 14px;border-top:1px solid var(--line);color:#4c4955;font-size:13px}.table tbody tr:hover{background:#fbfafd}.person{display:flex;align-items:center;gap:10px}.avatar{width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:var(--violet-soft);color:var(--violet);font-size:10px;font-weight:700}.person strong{display:block;color:var(--ink);font-size:13px}.person small{display:block;color:var(--muted);font-size:11px}.pill{display:inline-flex;padding:3px 8px;border-radius:999px;background:#f4f3f7;color:#686572;font-size:10px;font-weight:600;text-transform:capitalize}.pill.high,.pill.urgent,.pill.needs_attention{background:var(--red-soft);color:var(--red)}.pill.open,.pill.new{background:var(--amber-soft);color:var(--amber)}.pill.resolved,.pill.vip,.pill.active{background:var(--mint-soft);color:#158369}.linkbtn{min-height:32px;border:0;background:transparent;color:var(--violet);font-size:12px;font-weight:600}.pagination{min-height:54px;padding:9px 14px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.pager{display:flex;gap:6px}.pager button{min-width:34px;height:34px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink)}.pager button:disabled{opacity:.4;cursor:not-allowed}
    .case-list{display:grid}.case{padding:14px 16px;border-bottom:1px solid var(--line)}.case:last-child{border-bottom:0}.case-top,.case-foot{display:flex;align-items:center;justify-content:space-between;gap:10px}.case-id{color:var(--muted);font-size:10px}.case h3{margin:8px 0 3px;font-size:13px}.case p{margin:0;color:var(--muted);font-size:11px;line-height:1.4}.case-foot{margin-top:10px}.assignee{min-width:0;color:var(--muted);font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.case select{height:30px;max-width:120px;border:1px solid var(--line);border-radius:7px;background:#fff;color:var(--ink);font-size:11px}.activity-list{display:grid}.activity{padding:11px 15px;border-bottom:1px solid var(--line)}.activity:last-child{border-bottom:0}.activity p{margin:0;color:#4c4955;font-size:12px}.activity small{display:block;margin-top:3px;color:var(--muted);font-size:10px}
    .empty{padding:26px;color:var(--muted);font-size:12px;text-align:center}.loader{display:grid;place-items:center;min-height:50vh;color:var(--muted)}.toast{position:fixed;right:24px;bottom:24px;z-index:60;padding:11px 14px;border:1px solid #b8ded3;border-radius:9px;background:#effbf7;color:#15765f;box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:opacity .16s ease-out,transform .16s ease-out}.toast.show{opacity:1;transform:none}.modal{position:fixed;inset:0;z-index:50;display:none;place-items:center;padding:18px;background:rgba(32,29,50,.45);backdrop-filter:blur(4px)}.modal.open{display:grid}.dialog{width:min(540px,100%);max-height:90vh;overflow:auto;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:var(--shadow)}.dialog-head{display:flex;align-items:center;justify-content:space-between;padding:17px 19px;border-bottom:1px solid var(--line)}.dialog-head h2{margin:0;font-size:16px}.close{width:40px;height:40px;border:0;border-radius:50%;background:transparent;color:var(--muted);font-size:20px}.form{padding:18px;display:grid;grid-template-columns:1fr 1fr;gap:13px}.field{display:grid;gap:5px}.field.full{grid-column:1/-1}.field label{font-size:12px;font-weight:600}.field input,.field select,.field textarea{width:100%;min-height:40px;padding:8px 10px;border:1px solid var(--line-strong);border-radius:8px;background:#fff;color:var(--ink);font-size:13px}.field textarea{min-height:78px;resize:vertical}.form-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:8px;padding-top:5px}.drawer{position:fixed;inset:0;z-index:45;display:none;background:rgba(32,29,50,.35)}.drawer.open{display:block}.drawer-panel{position:absolute;inset:0 0 0 auto;width:min(470px,100%);overflow:auto;background:#fff;box-shadow:var(--shadow)}.drawer-top{padding:18px 20px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.drawer-body{padding:20px}.profile{display:flex;align-items:center;gap:12px;margin-bottom:18px}.profile .avatar{width:48px;height:48px;font-size:14px}.profile h2{margin:0;font-size:20px}.profile p{margin:2px 0 0;color:var(--muted);font-size:12px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);border-radius:10px;overflow:hidden}.detail{padding:11px}.detail:nth-child(odd){border-right:1px solid var(--line)}.detail:nth-child(-n+2){border-bottom:1px solid var(--line)}.detail span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase}.detail strong{display:block;margin-top:3px;font-size:13px}.subhead{margin:20px 0 8px;color:var(--muted);font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase}.tag{display:inline-block;margin:0 5px 5px 0;padding:4px 7px;border-radius:7px;background:var(--violet-soft);color:var(--violet);font-size:10px}
    @media(max-width:1100px){.topbar{grid-template-columns:180px 1fr 180px}.dashboard{grid-template-columns:1fr}.sidecol{grid-template-columns:1fr 1fr}.metrics{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:760px){.page{padding:0}.shell{min-height:100vh;border:0;border-radius:0}.topbar{height:auto;padding:14px;display:flex;align-items:center;justify-content:space-between}.topnav{display:none}.top-actions .sync,.logout{display:none}.body{padding:0 12px 24px}.heading{height:auto;padding:18px 0}.heading p{display:none}.dashboard{display:block}.maincol,.sidecol{display:block}.metrics{grid-template-columns:1fr;margin-bottom:12px}.metric{min-height:auto;border-right:0;border-bottom:1px solid var(--line)}.metric:last-child{border-bottom:0}.metric-value{margin-top:10px}.panel{margin-bottom:12px}.sidecol{margin-top:12px}.search,.search input{width:100%}.panel-head{align-items:flex-start;flex-direction:column}.form{grid-template-columns:1fr}.field.full,.form-actions{grid-column:auto}.detail-grid{grid-template-columns:1fr}.detail:nth-child(n){border-right:0;border-bottom:1px solid var(--line)}.detail:last-child{border-bottom:0}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.toast{transition:none}}
  </style>
</head>
<body>
<div class="page"><div class="shell">
  <header class="topbar">
    <a class="brand" href="/crm"><span class="brandmark">PP</span><span>Pleasure Pizza</span></a>
    <nav class="topnav"><button class="active" data-target="overview">Overview</button><button data-target="customers">Customers</button><button data-target="cases">Support</button><a class="btn-small" href="/" title="${safeOrigin}/mcp">MCP</a></nav>
    <div class="top-actions"><div class="sync"><span class="sync-dot waiting" id="syncDot"></span><span id="syncStatus">Connecting</span></div><form method="post" action="/crm/logout"><button class="logout" type="submit">Sign out</button></form></div>
  </header>
  <main class="body" aria-label="Customer operations">
    <div class="heading"><div><h1>Customer overview</h1><p>Live customer profiles, support cases, and recent activity</p></div><button class="btn btn-primary" id="newCustomer">Add customer</button></div>
    <div id="appContent"><div class="loader">Loading customer workspace…</div></div>
  </main>
</div></div>

<div class="modal" id="customerModal"><div class="dialog"><div class="dialog-head"><h2>Add customer</h2><button class="close" data-close aria-label="Close">×</button></div><form class="form" id="customerForm">
  <div class="field"><label for="customerName">Name</label><input id="customerName" name="name" required autocomplete="name"></div><div class="field"><label for="customerEmail">Email</label><input id="customerEmail" name="email" type="email" autocomplete="email"></div>
  <div class="field"><label for="customerPhone">Phone</label><input id="customerPhone" name="phone" autocomplete="tel"></div><div class="field"><label for="customerLocation">Home location</label><select id="customerLocation" name="location"><option value="pleasure_point">Pleasure Point</option><option value="east_side">East Side</option><option value="downtown">Downtown</option></select></div>
  <div class="field full"><label for="customerTags">Tags, separated by commas</label><input id="customerTags" name="tags" placeholder="vegetarian, delivery"></div><div class="form-actions"><button class="btn" type="button" data-close>Cancel</button><button class="btn btn-primary" type="submit">Create customer</button></div>
</form></div></div>
<div class="modal" id="caseModal"><div class="dialog"><div class="dialog-head"><h2>Create support case</h2><button class="close" data-close aria-label="Close">×</button></div><form class="form" id="caseForm">
  <div class="field full"><label for="caseCustomer">Customer</label><select name="customerId" id="caseCustomer" required></select></div><div class="field full"><label for="caseSubject">Subject</label><input id="caseSubject" name="subject" required></div>
  <div class="field"><label for="casePriority">Priority</label><select id="casePriority" name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></div><div class="field"><label for="caseAssignee">Assigned team</label><select id="caseAssignee" name="assignedTo"><option>Unassigned</option><option>Pleasure Point team</option><option>East Side team</option><option>Downtown team</option></select></div>
  <div class="field full"><label for="caseMessage">Details</label><textarea id="caseMessage" name="message"></textarea></div><div class="form-actions"><button class="btn" type="button" data-close>Cancel</button><button class="btn btn-primary" type="submit">Create case</button></div>
</form></div></div>
<div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-top"><strong>Customer profile</strong><button class="close" id="closeDrawer" aria-label="Close">×</button></div><div class="drawer-body" id="drawerBody"></div></div></div>
<div class="toast" id="toast" role="status"></div>

<script>
  const PAGE_SIZE=12;
  const state={data:null,query:'',page:1,syncing:false,eventSource:null,drawerCustomerId:null};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const label=value=>String(value??'').split('_').map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');
  const initials=name=>String(name).trim().split(' ').filter(Boolean).map(part=>part[0]).join('').slice(0,2).toUpperCase();
  const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);
  const ago=value=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return 'just now';if(seconds<3600)return Math.floor(seconds/60)+'m ago';if(seconds<86400)return Math.floor(seconds/3600)+'h ago';return Math.floor(seconds/86400)+'d ago'};
  async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===401){location.href='/crm/login';throw new Error('Your CRM session expired.')}const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'Request failed');return body}
  function toast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.style.borderColor=error?'#edbbc4':'#b8ded3';el.style.background=error?'#fff0f3':'#effbf7';el.style.color=error?'#a43c4f':'#15765f';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
  function customerOptions(selected=''){return state.data.customers.map(c=>'<option value="'+esc(c.id)+'" '+(c.id===selected?'selected':'')+'>'+esc(c.name)+' · '+esc(label(c.location))+'</option>').join('')}
  function filteredCustomers(){const q=state.query.toLowerCase();return state.data.customers.filter(c=>!q||[c.name,c.email,c.phone,c.location,...c.tags].join(' ').toLowerCase().includes(q))}
  function pagedCustomers(){const rows=filteredCustomers();const max=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));state.page=Math.min(state.page,max);return {rows:rows.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE),total:rows.length,max}}
  function renderCustomerRows(){const page=pagedCustomers();if(!page.rows.length)return '<tr><td colspan="6" class="empty">No customers match this search.</td></tr>';return page.rows.map(c=>'<tr><td><div class="person"><span class="avatar">'+esc(initials(c.name))+'</span><span><strong>'+esc(c.name)+'</strong><small>'+esc(c.email||c.phone||'No contact information')+'</small></span></div></td><td>'+esc(label(c.location))+'</td><td><span class="pill '+esc(c.status)+'">'+esc(label(c.status))+'</span></td><td>'+c.lifetimeOrders+'</td><td>'+money(c.lifetimeSpend)+'</td><td><button class="linkbtn view-customer" data-id="'+esc(c.id)+'">View</button></td></tr>').join('')}
  function renderCases(){if(!state.data.cases.length)return '<div class="empty">No support cases.</div>';return state.data.cases.slice(0,6).map(item=>{const customer=state.data.customers.find(c=>c.id===item.customerId);return '<article class="case"><div class="case-top"><span class="case-id">'+esc(item.id)+'</span><span class="pill '+esc(item.priority)+'">'+esc(item.priority)+'</span></div><h3>'+esc(item.subject)+'</h3><p>'+esc(item.message||'No additional details.')+'</p><div class="case-foot"><span class="assignee">'+esc(customer?.name||'Unknown customer')+' · '+esc(item.assignedTo)+'</span><select class="case-status" data-id="'+esc(item.id)+'" aria-label="Case status"><option value="open" '+(item.status==='open'?'selected':'')+'>Open</option><option value="in_progress" '+(item.status==='in_progress'?'selected':'')+'>In progress</option><option value="waiting" '+(item.status==='waiting'?'selected':'')+'>Waiting</option><option value="resolved" '+(item.status==='resolved'?'selected':'')+'>Resolved</option></select></div></article>'}).join('')}
  function renderActivities(){if(!state.data.activities.length)return '<div class="empty">No activity yet.</div>';return state.data.activities.slice(0,7).map(a=>'<div class="activity"><p>'+esc(a.summary)+'</p><small>'+ago(a.createdAt)+'</small></div>').join('')}
  function renderPagination(){const page=pagedCustomers();const start=page.total?(state.page-1)*PAGE_SIZE+1:0;const end=Math.min(state.page*PAGE_SIZE,page.total);document.getElementById('pageSummary').textContent=start+'–'+end+' of '+page.total+' customers';document.getElementById('prevPage').disabled=state.page<=1;document.getElementById('nextPage').disabled=state.page>=page.max}
  function render(){const d=state.data;document.getElementById('appContent').innerHTML='<div class="dashboard"><div class="maincol"><section class="metrics" id="overview"><div class="metric"><div class="metric-head"><span class="metric-label">Customers</span><span class="delta">Live</span></div><div class="metric-value" id="statCustomers">'+d.stats.customers+'<span class="metric-note">profiles</span></div></div><div class="metric"><div class="metric-head"><span class="metric-label">Customer value</span><span class="delta">Demo</span></div><div class="metric-value" id="statRevenue">'+money(d.stats.lifetimeRevenue)+'</div></div><div class="metric"><div class="metric-head"><span class="metric-label">Open cases</span><span class="delta attention" id="attentionDelta">'+d.stats.urgentCases+' priority</span></div><div class="metric-value" id="statOpenCases">'+d.stats.openCases+'<span class="metric-note">active</span></div></div></section><section class="panel" id="customers"><div class="panel-head"><div><h2>Customer directory</h2><p>Shared by the web app, CLI, and MCP</p></div><div class="search"><input id="customerSearch" value="'+esc(state.query)+'" aria-label="Search customers" placeholder="Search customers"></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Location</th><th>Status</th><th>Orders</th><th>Value</th><th></th></tr></thead><tbody id="customerRows">'+renderCustomerRows()+'</tbody></table></div><div class="pagination"><span id="pageSummary"></span><div class="pager"><button id="prevPage" aria-label="Previous page">←</button><button id="nextPage" aria-label="Next page">→</button></div></div></section></div><aside class="sidecol"><section class="panel" id="cases"><div class="panel-head"><div><h2>Priority support</h2><p>Cases needing staff attention</p></div><button class="btn btn-small" id="newCase">New case</button></div><div class="case-list" id="caseList">'+renderCases()+'</div></section><section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p id="lastSync">Waiting for live sync</p></div></div><div class="activity-list" id="activityList">'+renderActivities()+'</div></section></aside></div>';
    bindDynamic();renderPagination();
  }
  function setSyncStatus(mode,message){const dot=document.getElementById('syncDot');dot.className='sync-dot'+(mode==='waiting'?' waiting':mode==='offline'?' offline':'');document.getElementById('syncStatus').textContent=message}
  function updateDirectory(){document.getElementById('customerRows').innerHTML=renderCustomerRows();renderPagination();bindCustomerButtons()}
  function updateLive(next){const selectedCase=document.getElementById('caseCustomer')?.value||'';state.data=next;if(state.drawerCustomerId&&!next.customers.some(customer=>customer.id===state.drawerCustomerId))closeDrawer();document.getElementById('statCustomers').firstChild.textContent=next.stats.customers;document.getElementById('statRevenue').textContent=money(next.stats.lifetimeRevenue);document.getElementById('statOpenCases').firstChild.textContent=next.stats.openCases;document.getElementById('attentionDelta').textContent=next.stats.urgentCases+' priority';updateDirectory();document.getElementById('caseList').innerHTML=renderCases();document.getElementById('activityList').innerHTML=renderActivities();const caseCustomer=document.getElementById('caseCustomer');if(caseCustomer)caseCustomer.innerHTML=customerOptions(selectedCase);bindCaseStatuses();document.getElementById('lastSync').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'});setSyncStatus('live','Live')}
  function bindCaseStatuses(){document.querySelectorAll('.case-status').forEach(select=>select.addEventListener('change',async()=>{try{await api('/api/crm/cases/'+select.dataset.id,{method:'PATCH',body:JSON.stringify({status:select.value})});toast('Case updated');await refresh()}catch(error){toast(error.message,true)}}))}
  function bindDynamic(){document.getElementById('customerSearch').addEventListener('input',event=>{state.query=event.target.value;state.page=1;updateDirectory()});document.getElementById('prevPage').onclick=()=>{state.page-=1;updateDirectory()};document.getElementById('nextPage').onclick=()=>{state.page+=1;updateDirectory()};bindCustomerButtons();bindCaseStatuses();document.getElementById('newCase').onclick=()=>openModal('caseModal')}
  function bindCustomerButtons(){document.querySelectorAll('.view-customer').forEach(button=>button.onclick=()=>showCustomer(button.dataset.id))}
  async function refresh(){if(state.syncing)return;state.syncing=true;try{const next=await api('/api/crm/dashboard');if(!state.data){state.data=next;render();document.getElementById('lastSync').textContent='Updated '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'})}else updateLive(next)}finally{state.syncing=false}}
  let refreshTimer;function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(error=>{setSyncStatus('offline','Reconnecting');console.error(error)}),80)}
  function connectLive(){if(!window.EventSource){setSyncStatus('waiting','Periodic sync');return}const source=new EventSource('/api/crm/events');state.eventSource=source;source.addEventListener('ready',()=>setSyncStatus('live','Live'));source.addEventListener('crm-change',scheduleRefresh);source.onopen=()=>setSyncStatus('live','Live');source.onerror=()=>setSyncStatus('offline','Reconnecting')}
  function closeDrawer(){document.getElementById('drawer').classList.remove('open');document.getElementById('drawerBody').replaceChildren();state.drawerCustomerId=null}
  async function showCustomer(id){try{const c=await api('/api/crm/customers/'+id);document.getElementById('drawerBody').innerHTML='<div class="profile"><span class="avatar">'+esc(initials(c.name))+'</span><div><h2>'+esc(c.name)+'</h2><p>'+esc(c.email||'No email')+' · '+esc(c.phone||'No phone')+'</p></div></div><div class="detail-grid"><div class="detail"><span>Home location</span><strong>'+esc(label(c.location))+'</strong></div><div class="detail"><span>Loyalty</span><strong>'+esc(c.loyaltyTier)+'</strong></div><div class="detail"><span>Orders</span><strong>'+c.lifetimeOrders+'</strong></div><div class="detail"><span>Lifetime value</span><strong>'+money(c.lifetimeSpend)+'</strong></div></div><div class="subhead">Tags</div><div>'+(c.tags.length?c.tags.map(t=>'<span class="tag">'+esc(t)+'</span>').join(''):'<span class="tag">No tags</span>')+'</div><div class="subhead">Open cases</div>'+(c.cases.filter(item=>item.status!=='resolved').map(item=>'<div class="activity"><p>'+esc(item.subject)+'</p><small>'+esc(label(item.status))+'</small></div>').join('')||'<div class="empty">No open cases.</div>')+'<div class="subhead">Recent timeline</div>'+c.activities.slice(0,7).map(a=>'<div class="activity"><p>'+esc(a.summary)+'</p><small>'+ago(a.createdAt)+'</small></div>').join('')+'<div style="display:flex;justify-content:flex-end;margin-top:20px"><button class="btn btn-danger btn-small" id="deleteCustomer">Remove demo customer</button></div>';state.drawerCustomerId=c.id;document.getElementById('drawer').classList.add('open');document.getElementById('deleteCustomer').onclick=async()=>{if(!confirm('Remove '+c.name+' and linked demo cases?'))return;try{await api('/api/crm/customers/'+c.id,{method:'DELETE'});closeDrawer();toast('Demo customer removed');await refresh()}catch(error){toast(error.message,true)}}}catch(error){toast(error.message,true)}}
  function openModal(id){document.getElementById('caseCustomer').innerHTML=customerOptions();document.getElementById(id).classList.add('open')}
  function closeModals(){document.querySelectorAll('.modal').forEach(modal=>modal.classList.remove('open'))}
  document.getElementById('newCustomer').onclick=()=>openModal('customerModal');document.querySelectorAll('[data-close]').forEach(button=>button.onclick=closeModals);document.querySelectorAll('.modal').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeModals()}));document.getElementById('closeDrawer').onclick=closeDrawer;document.getElementById('drawer').addEventListener('click',event=>{if(event.target.id==='drawer')closeDrawer()});document.querySelectorAll('[data-target]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-target]').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})});
  document.getElementById('customerForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);try{await api('/api/crm/customers',{method:'POST',body:JSON.stringify({name:form.get('name'),email:form.get('email'),phone:form.get('phone'),location:form.get('location'),tags:String(form.get('tags')||'').split(',').map(v=>v.trim()).filter(Boolean)})});event.target.reset();closeModals();toast('Customer added');await refresh()}catch(error){toast(error.message,true)}};
  document.getElementById('caseForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);try{await api('/api/crm/cases',{method:'POST',body:JSON.stringify(Object.fromEntries(form.entries()))});event.target.reset();closeModals();toast('Support case created');await refresh()}catch(error){toast(error.message,true)}};
  refresh().then(connectLive).catch(error=>{document.getElementById('appContent').innerHTML='<div class="empty">Could not load CRM: '+esc(error.message)+'</div>';setSyncStatus('offline','Connection failed')});
  setInterval(()=>refresh().catch(()=>{}),15000);
</script>
</body>
</html>`;
}
